OBJECTS : add.o subtract.o multiply.o divide.o

add.o : add.c
	cd lib
	gcc -c add.c

subtract.o : subtract.c
	cd lib
	gcc -c subtract.o

multiply.o : multiply.c
	cd lib
	gcc -c multiply.c

divide.o : divide.c
	cd lib
	gcc -c divide.c

clean : 
	cd lib
	rm -f *.o
